### ISSUE TITLE
Error: Unsupported body payload object

### ISSUE THREAD

**Issue by Omnyx** [erento/nestjs-modules#13]
Hi, first of all this is an amazing module. Looking forward for the next updates.

I am trying to use AWS S3 client but I am receiving the error message: Error: Unsupported body payload object

What I am doing is:

consumer service: 
```
 async uploadImage(file: any) : Promise<any> {
        return await this.S3Client.upload('folder',file);
    }
```
consumer controller: 
```
@Post('upload')
    @ApiImplicitFile({name: 'file'})
    @UseInterceptors(FileInterceptor('file'))
    async upload(@UploadedFile() file){
        try{
            return await this.consumerService.uploadImage(file);
        } catch (error){
            console.log(error);
        }
    }
```
the playload object structure I a receiving when running the debugger is: 

![image](https://user-images.githubusercontent.com/54276812/66524579-d3d3bc00-eac0-11e9-839e-185f73a7e6c0.png)

any ideas?

**Comment by rokerkony** [comment]
Hi,
thank you for reaching to us.

Currently, our typing is disallowing uploading `UploadedFile` because we didn't have a use case for it but it is fairly easy to do that so we will prepare a required change.

In the meantime you can still use it with `<any>` as follows (see `.buffer` after the file):

```ts
try {
    return await this.s3Client.upload('folder/file-name.jpg', <any> file.buffer);
} catch (e) {
    throw new InternalServerErrorException('uplaod failed');
}
```

I would also recommend adding types for uploaded files:
```ts
@UploadedFile() file: Express.Multer.File,
```
this requires to install dev dependency: `npm i --save-dev @types/multer`
